import type { Metadata } from "next";
import { Red_Hat_Display, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-libreBaskerville",
});

export const metadata: Metadata = {
  title: "Glitcheese Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.className} ${libreBaskerville.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
